name: mobKillStats
version: '1.0-SNAPSHOT'
main: org.austin1965.mobKillStats.MobKillStats
api-version: '1.21'

commands:
  mobkillstats:
      description: something
      usage: /<command>
      permission:  mobkillstats.readkills